/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.venolabs.mietwagen.ui.component;

import com.venolabs.mietwagen.ui.MainFrame;
import com.venolabs.mietwagen.ui.handlers.MouseHandler;

/**
 *
 * @author sergio
 */
public class SideBar extends javax.swing.JPanel {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form SideBar
     */
    public SideBar() {
        initComponents();
        
        lbHome.addMouseListener(new MouseHandler() );
        lbCarManagement.addMouseListener(new MouseHandler() );
        lbClientManagement.addMouseListener(new MouseHandler() );
        lbRentACar.addMouseListener(new MouseHandler() );
        lbReturn.addMouseListener(new MouseHandler() );
        lbRents.addMouseListener(new MouseHandler() );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        lbHome = new javax.swing.JLabel();
        lbRentACar = new javax.swing.JLabel();
        lbReturn = new javax.swing.JLabel();
        lbRents = new javax.swing.JLabel();
        lbClientManagement = new javax.swing.JLabel();
        lbCarManagement = new javax.swing.JLabel();

        setBackground(new java.awt.Color(250, 200, 1));
        setPreferredSize(new java.awt.Dimension(64, 575));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        lbHome.setBackground(new java.awt.Color(250, 200, 1));
        lbHome.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lbHome.setForeground(java.awt.Color.white);
        lbHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        lbHome.setOpaque(true);
        lbHome.setPreferredSize(new java.awt.Dimension(64, 64));
        lbHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbHomeMouseEntered(evt);
            }
        });
        add(lbHome);

        lbRentACar.setBackground(new java.awt.Color(250, 200, 1));
        lbRentACar.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lbRentACar.setForeground(java.awt.Color.white);
        lbRentACar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbRentACar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rent_a_car.png"))); // NOI18N
        lbRentACar.setOpaque(true);
        lbRentACar.setPreferredSize(new java.awt.Dimension(64, 64));
        lbRentACar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbRentACarMouseEntered(evt);
            }
        });
        add(lbRentACar);

        lbReturn.setBackground(new java.awt.Color(250, 200, 1));
        lbReturn.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lbReturn.setForeground(java.awt.Color.white);
        lbReturn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/return_a_car.png"))); // NOI18N
        lbReturn.setOpaque(true);
        lbReturn.setPreferredSize(new java.awt.Dimension(64, 64));
        lbReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbReturnMouseEntered(evt);
            }
        });
        add(lbReturn);

        lbRents.setBackground(new java.awt.Color(250, 200, 1));
        lbRents.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lbRents.setForeground(java.awt.Color.white);
        lbRents.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbRents.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rents.png"))); // NOI18N
        lbRents.setOpaque(true);
        lbRents.setPreferredSize(new java.awt.Dimension(64, 64));
        lbRents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbRentsMouseEntered(evt);
            }
        });
        add(lbRents);

        lbClientManagement.setBackground(new java.awt.Color(250, 200, 1));
        lbClientManagement.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lbClientManagement.setForeground(java.awt.Color.white);
        lbClientManagement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbClientManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clients.png"))); // NOI18N
        lbClientManagement.setOpaque(true);
        lbClientManagement.setPreferredSize(new java.awt.Dimension(64, 64));
        lbClientManagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbClientManagementMouseEntered(evt);
            }
        });
        add(lbClientManagement);

        lbCarManagement.setBackground(new java.awt.Color(250, 200, 1));
        lbCarManagement.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lbCarManagement.setForeground(java.awt.Color.white);
        lbCarManagement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCarManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cars.png"))); // NOI18N
        lbCarManagement.setOpaque(true);
        lbCarManagement.setPreferredSize(new java.awt.Dimension(64, 64));
        lbCarManagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbCarManagementMouseEntered(evt);
            }
        });
        add(lbCarManagement);
    }

    private void lbHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbHomeMouseEntered
        MainFrame.INSTANCE.home();
    }//GEN-LAST:event_lbHomeMouseEntered

    private void lbRentACarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbRentACarMouseEntered
        MainFrame.INSTANCE.show(MainFrame.RENT_A_CAR_SCREEN);
    }//GEN-LAST:event_lbRentACarMouseEntered

    private void lbReturnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbReturnMouseEntered
        MainFrame.INSTANCE.show(MainFrame.RETURN_SCREEN);
    }//GEN-LAST:event_lbReturnMouseEntered

    private void lbRentsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbRentsMouseEntered
        MainFrame.INSTANCE.show(MainFrame.RENTS_SCREEN);
    }//GEN-LAST:event_lbRentsMouseEntered

    private void lbClientManagementMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbClientManagementMouseEntered
        MainFrame.INSTANCE.show(MainFrame.CLIENT_SCREEN);
    }//GEN-LAST:event_lbClientManagementMouseEntered

    private void lbCarManagementMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCarManagementMouseEntered
        MainFrame.INSTANCE.show(MainFrame.CAR_SCREEN);
    }//GEN-LAST:event_lbCarManagementMouseEntered


    
    private javax.swing.JLabel lbCarManagement;
    private javax.swing.JLabel lbClientManagement;
    private javax.swing.JLabel lbHome;
    private javax.swing.JLabel lbRentACar;
    private javax.swing.JLabel lbRents;
    private javax.swing.JLabel lbReturn;
    
}
